### PR TITLE
Fix: #1547: whenWillCloseDo: block is evaluated twice when closing a window 

### PR DESCRIPTION
**Pull request by Ducasse**
We decided to remove the closeDiscardingChanges from Spec

### CODE REVIEW

**Comment by Ducasse** [comment]
This is a potential backport to P12.

**Comment by estebanlm** [comment]
please do not merge this, I let a comment in the reported issue.

**Comment by MarcusDenker** [comment]
What is important, too: please add a better name tan "Fix: #1547" (this looks very bad in the weekly email, too)

**Comment by Ducasse** [comment]
Right now the code of the book breaks.

**Comment by estebanlm** [comment]
> Right now the code of the book breaks.

can you point me to the example that breaks ?

**Comment by Ducasse** [comment]
@koendehondt Do you remember this is in the window chapter?

**Comment by koendehondt** [comment]
> > Right now the code of the book breaks.
> 
> can you point me to the example that breaks ?

The example in the description of https://github.com/pharo-spec/Spec/issues/1547 exposes the bug.

The code in the book is in section 9.3 "Preventing window close". The corresponding code is in class `WindowExamplePresenter2` in the [code repo](https://github.com/SquareBracketAssociates/CodeOfSpec20Book/blob/master/src/CodeOfSpec20Book/WindowExamplePresenter2.class.st). The class comment links to https://github.com/pharo-spec/Spec/issues/1547 to indicate that the example does not work.

**Comment by estebanlm** [comment]
This is fixed upstream (I applied same thing)

**Comment by koendehondt** [comment]
> This is fixed upstream (I applied same thing)

Could you post the commit here? Thanks.

**Pull request closed without merging**
