### PR TITLE
Raw fix to correctly show the references to pool variables from the d…

### PR DESCRIPTION
**Pull request by arturozambrano**
…ebugger.

Other variables are still not correctly handled (the code was already flagged as buggy).
Before
image
After
image.png

### CODE REVIEW

**Comment by estebanlm** [comment]
tests do not pass

**Comment by arturozambrano** [comment]
The 3 tests that did not pass before now pass.

**Comment by Ducasse** [comment]
HI arturo why did you close this issue? was is integrated?

**Comment by arturozambrano** [comment]
I will do the full thing. It was just a dirty patch to show what I meant
and discuss. I will work on the actual solution and create a new PR.
Best regards.

**Pull request closed without merging**
