### PR TITLE
667-PolyWidget-SpChooseMethod-improvement

### LINKED ISSUE #667: PolyWidget SpChooseMethod improvement
I migrate the externalBrowse so I need a class/method/package/protocol navigation system

so I decided to improve the SpChooseMethodUI by: 
* adding protocols List 

If you have idea comment this issue

### PR DESCRIPTION
**Pull request by CafeKrem**
fix #667

### CODE REVIEW

**Comment by CafeKrem** [comment]
if you have any suggestion tell me.

**Comment by CafeKrem** [comment]
it's strange in my image it's all test pass

**Comment by jecisc** [comment]
It fails locally for me.

**Comment by jecisc** [comment]
In a test, you use a package that is not present in Pharo.

**Comment by jecisc** [comment]
I'll fix it.

**Pull request merged**
