### PR TITLE
remove more unsent methods that send non-existing selectors. 

### PR DESCRIPTION
**Pull request by MarcusDenker**
This is dead code.

### CODE REVIEW

**Comment by Ducasse** [comment]
Looks good to me but I'm not spec expert.

**Review by estebanlm — APPROVED** [review]

**Comment by estebanlm** [comment]
but there are dependencies affected.

**Review by estebanlm — CHANGES_REQUESTED** [review]
for some reason there are dependencies that seems accepted.

**Comment by MarcusDenker** [comment]
This is not due to this change, this is failing since some time

https://github.com/pharo-spec/Spec/issues/1415

**Comment by estebanlm** [comment]
there are all these affected: 

 ✗ #testCollectionsShouldNotDependOnRandom (1263ms)
 ✗ #testExternalBasicToolsDependencies (1251ms)
 ✗ #testExternalCompilerDependencies (1252ms)
 ✗ #testExternalDisplayDependencies (1279ms)
 ✗ #testExternalFileSystemDependencies (1239ms)
 ✗ #testExternalIDEDependencies (1362ms)
 ✗ #testExternalKernelDependencies (1250ms)
 ✗ #testExternalLocalMonticelloDependencies (1236ms)
 ✗ #testExternalMetacelloDependencies (1239ms)
 ✗ #testExternalMonticelloDependencies (1246ms)
 ✗ #testExternalMorphicCoreDependencies (1238ms)
 ✗ #testExternalMorphicDependencies (1232ms)
 ✗ #testExternalSUnitDependencies (1255ms)
 ✗ #testExternalSUnitKernelDependencies (1227ms)
 ✗ #testExternalSpec2Dependencies (1249ms)
 ✗ #testExternalUFFIDependencies (1226ms)
 ✗ #testExternalUIDependencies (1398ms)
 ✗ #testFilesShouldNotDependOnRandom (1347ms)

**Comment by MarcusDenker** [comment]
yes, this is failing for all the PRs, not just this one.

**Comment by jecisc** [comment]
I found the origin of this problem and I and currently doing a PR to Pharo. I tried to find the problem since a long time but I just fount it yesterday.

**Comment by jecisc** [comment]
This should fix by https://github.com/pharo-project/pharo/pull/14404 (I hope)

**Comment by jecisc** [comment]
Only two unrelated failures left

**Pull request merged**
