### PR TITLE
Extend SpDiffPresenter to make it navigable accross differences

### PR DESCRIPTION
**Pull request by sonibla**
Add Top, Next difference, Previous difference in SpDiffPresenter to easily navigate

navigableDiffPresenter

https://github.com/pharo-project/pharo/pull/11641 required! (because I had to change the morphic class DiffMorph)

Defult behavior of SpDiffPresenter unchanged (by default no buttons will show up)

### CODE REVIEW

**Comment by Ducasse** [comment]
was merged

**Comment by sonibla** [comment]
This feature needs both https://github.com/pharo-project/pharo/pull/11641 and https://github.com/pharo-spec/Spec/pull/1305
https://github.com/pharo-spec/Spec/pull/1305 wasn't merged

**Comment by MarcusDenker** [comment]
I re-opened this PR

**Comment by Ducasse** [comment]
So is it working because the tests are green.

**Comment by jecisc** [comment]
This is causing an issue with the wrapping: https://github.com/pharo-project/pharo/issues/14640

**Pull request merged**
