### PR TITLE
Fix scrollTo: on SpScrollableLayout not working

### PR DESCRIPTION
**Pull request by hernanmd**
Add SpMorphicScrollableAdapter>>scrollTo:
Add example in class documentation.

### CODE REVIEW

**Comment by estebanlm** [comment]
Sorry for coming to this so late.
there is a problem with this: in the Gtk implementation (which arrived first, this time :P) the scroll value is not a number between 0 and 1 but a real offset. 
To keep the same criteria, you need to receive also a real offsent then transform it into the percent value (which is what the 0..1 value is) in the adapter.

**Review by estebanlm — CHANGES_REQUESTED** [review]
what I set in comment ;)

**Comment by hernanmd** [comment]
@estebanlm 

I've seen the changes should be applied to `GtkScrollableAdapter>>scrollTo:`.
I should get then the maximum offset of the adapter which holds the scroller?
Any hints?

**Comment by hernanmd** [comment]
> Sorry for coming to this so late. there is a problem with this: in the Gtk implementation (which arrived first, this time :P) the scroll value is not a number between 0 and 1 but a real offset. To keep the same criteria, you need to receive also a real offsent then transform it into the percent value (which is what the 0..1 value is) in the adapter.

I don't know how to adapt this method for the GTK version (I tried and it is not working).
Could we have this integrated anyway as this is needed for the NewTools File Browser? Since @jecisc worked in the File Browser too what do you think ?

**Comment by Ducasse** [comment]
Hernan is it not that the adpater should do the conversion following the way it is done in GTK backend. 
We specify X in the presenter and x goes to GTKbackend and a transformation of (X) to the morphic one?

**Comment by estebanlm** [comment]
do not care about Gtk backend. 
I was thinking the opposite: you need to do the morphic backend to accept a real offset and internally (in the adapter) transform it into a percentage (since you will have the data needed there).

**Comment by Ducasse** [comment]
Ok thanks. Now this is clearer.

**Comment by Ducasse** [comment]
So what do we do with this one.

**Comment by estebanlm** [comment]
I asked for some changes...

**Comment by hernanmd** [comment]
> I asked for some changes...

Sorry, I never got quite right how to implement them.
Do you think we could sync this week?

**Comment by Ducasse** [comment]
@hernanmd | @estebanlm 
can you take action? @estebanlm if you know and it takes you 10 min can you do it because
I have the impression that @hernanmd does not understand or explain to him.

**Comment by estebanlm** [comment]
yeah, we will see it as soon as we are both in the same place ;)

**Comment by Ducasse** [comment]
ping! @hernanmd @estebanlm

**Comment by Ducasse** [comment]
Broken test is unrelated 

```
 ✗ #testUndeclared (165ms)
TestFailure: Found undeclared Variables: 
StSystemReporter in: SmalltalkCIPharo9>>#imageInfo
Gofer in: SCIGoferLoadSpec>>#basicLoadProjectOn:
ReleaseTest(TestAsserter)>>assert:description:resumable:
ReleaseTest(TestAsserter)>>assert:description:
ReleaseTest>>testUndeclared ...assert: remaining isEmpty description: description
ReleaseTest(TestCase)>>performTest
```

so I merge

**Comment by jecisc** [comment]
We have 2 failing tests about scrolling in the latest Pharo build. I think they come from here

**Pull request merged**
