### PR TITLE
merge some removals

### PR DESCRIPTION
**Pull request by estebanlm**

### CODE REVIEW

**Comment by Ducasse** [comment]
Can you show us :) the decoration?

**Comment by estebanlm** [comment]
This image: 

image

Is produced with this code: 

```Smalltalk
     SpListPresenter new
		items: self environment allClasses;
		displayIcon: [ :aClass | self iconNamed: aClass systemIconName  ];
		displayColor: [ :aClass | 
			(aClass name endsWith: 'Test')
				ifTrue: [ Color green ]
				ifFalse: [ Smalltalk ui theme textColor ] ];
		displayItalic: [ :aClass | aClass name includesSubstring: 'abstract' caseSensitive: false ];
		displayBold: [ :aClass | aClass hasSubclasses ];
		displayUnderline: [ :aClass | aClass numberOfMethods > 10 ];
		openWithSpec
```

(in SpListPresenter class>>exampleWithDecoratedString)

**Comment by estebanlm** [comment]
also, by adding one line you can have this: 

image

the line: 

```Smalltalk
     SpListPresenter new
	application: (SpApplication new useBackend: #Gtk);
	... etc....
```

**Comment by estebanlm** [comment]
I will reopen a PR later

**Pull request closed without merging**
