### PR TITLE
Rename the SpStyle hierarchy

### PR DESCRIPTION
**Pull request by NourDjihan**
Adding 'Style' at the end instead of the middle makes the class more clear to understand the fact that it's a style

### CODE REVIEW

**Comment by astares** [comment]
@NourDjihan Why do you close this? I would also vote for renaming, as 

- SpDrawStyle   
- SpGeometryStyle
- SpClassStyle
- SpContainerStyle
- ...

- SpStyleDraw   
- SpStyleGeometry
- SpStyleClass
- SpStyleContainer
- ...

would be more appropriate and clear. At the moment the SpStyleXXX is more used for grouping - but we should better use tags for grouping.

For instance in .NET there is a **FontStyle** Enum
https://docs.microsoft.com/en-us/dotnet/api/system.drawing.fontstyle?view=net-5.0
BorderStyle Enumeration
https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.borderstyle?view=net-5.0

Same in Java and other
Example for BorderStyle in well known POI library
https://poi.apache.org/apidocs/4.0/org/apache/poi/ss/usermodel/BorderStyle.html
...

If I remember correctly I once discussed this on Discord with Esteban. Was not able to convince him yet to follow what the "mainstream" does on this... but maybe more people could comment on this.

**Comment by NourDjihan** [comment]
Le mer. 21 avr. 2021 à 00:55, Astares ***@***.***> a écrit :

> @NourDjihan <https://github.com/NourDjihan> Why do you close this?
>
I have created a new one,

> I would also vote for renaming, as
>

>    - SpDrawStyle
>    - SpGeometryStyle
>    - SpClassStyle
>    - SpContainerStyle
>    - ...
>    seem to be better than:
>    - SpStyleDraw
>    - SpStyleGeometry
>    - SpStyleClass
>    - SpStyleContainer
>    - ...
>
> would be more appropriate and clear. At the moment the SpStyleXXX is more
> used for grouping - but we should better use tags for grouping.
>
For instance in .NET there is a *FontStyle* Enum
>
> https://docs.microsoft.com/en-us/dotnet/api/system.drawing.fontstyle?view=net-5.0
> BorderStyle Enumeration
>
> https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.borderstyle?view=net-5.0
>
> Same in Java and other
> Example for BorderStyle in well known POI library
>
> https://poi.apache.org/apidocs/4.0/org/apache/poi/ss/usermodel/BorderStyle.html
> ...
>
> If I remember correctly I once discussed this on Discord with Esteban. Was
> not able to convince him yet to follow what the "mainstream" does on
> this... but maybe more people could comment on this.
>
I have also made a PR for the SpStyle hierarchy, interesting ..

Nour

**Comment by estebanlm** [comment]
I am ok with this change (Sp*Style), but now there are conflicts :P 
can you re-made the PR, please?

**Comment by NourDjihan** [comment]
Done :)

>

**Pull request closed without merging**
