### PR TITLE
Cleanup/remove rename default spec to default layout refactoring

### PR DESCRIPTION
**Pull request by Ducasse**

### CODE REVIEW

**Comment by estebanlm** [comment]
seems that clean up is not letting the package really empty ?

**Comment by Ducasse** [comment]
I do not know. 
We will check.

**Comment by Ducasse** [comment]
Now the PR just remove one package so I do not know how it could stay and be not empty.

**Comment by Ducasse** [comment]
@balsa-sarenac I have the impression that you removed too much. 
Why do we remove the full package? 
I would not remove 
```
package: 'Spec2-Microdown' with: [ spec requires: #('SpecCore' 'Spec2-Adapters-Morphic') ];
```
Can you have a look?

**Comment by balsa-sarenac** [comment]
@Ducasse The package was empty after I have removed the class so I removed it as well.
Packages that are left are: `#('SpecCore' 'Spec2-Adapters-Morphic')`
I have only removed `#('Spec2-Transformations')`

**Comment by Ducasse** [comment]
Ok. Because on my machine it contains a lot of extensions.

**Comment by jecisc** [comment]
Should this be merged?

**Comment by estebanlm** [comment]
yeah, errors not related

**Pull request merged**
