### PR TITLE
Fix-Deprecated-sends

### PR DESCRIPTION
**Pull request by MarcusDenker**
When reading the build log I found some auto-transforms happening when running the tests

This PR commits these transforms

### CODE REVIEW

**Comment by MarcusDenker** [comment]
After doing this auto-transform, two transformed tests now fail:

 - #testUnselectedBlockExecutedWhenBecomeUnselected 
 -  #testUnselectedBlockNotExecutedWhenBecomeSelected

**Comment by estebanlm** [comment]
that's weird.

**Comment by demarey** [comment]
The API is not coherent.
A toggle button is now activated or not but the toggle button API uses `#beSelected`,  `#beUnselected` and `#isSelected` as well as a `selected` inst. var.
The change of `#whenSelectedDo` for `#whenActivatedDo`is not valid alone. We should change all or nothing

**Comment by demarey** [comment]
not really

```smalltalk
whenDeactivatedDo: aBlock
  "Inform when the button has been selected. 
   `aBlock` receives zero arguments."

  self whenChangedDo: [ :newSelectedValue | 
    newSelectedValue ifTrue: [ aBlock value ] ]

whenActivatedDo: aBlock
  "Inform when the button has been selected. 
   `aBlock` receives zero arguments."

  self whenChangedDo: [ :newSelectedValue | 
    newSelectedValue ifTrue: [ aBlock value ] ]
```
The implementation of `#whenDeactivatedDo:` and `#whenActivatedDo:`are the same!
I will commit the fix in https://github.com/pharo-spec/Spec/pull/1225

**Comment by estebanlm** [comment]
hah. Good catch. 
The problems of copy & pasting... :)

**Comment by MarcusDenker** [comment]
I close this as the other PR committed them all

**Pull request closed without merging**
