### PR TITLE
fix testIconProvider

### PR DESCRIPTION
**Pull request by estebanlm**

### CODE REVIEW

**Comment by Ducasse** [comment]
Esteban this is strange because I see this 
Capture 2022-09-21 at 21 20 27

**Comment by estebanlm** [comment]
yeah, I removed that line because it does not has sense anymore.
Now "command iconProvider" should be "command context application". I could add that validation but I just looked for a quick fix :P

**Comment by Ducasse** [comment]
But then why not removing the test. I do not see the point to have a test without assertion.

**Comment by estebanlm** [comment]
there are asserts :)
the complete test is like this: 

```Smalltalk
testIconProvider
	
	command iconProvider: self.
	
	self assert: command iconProvider equals: self.
	
	command iconName: #banana.
	self assert: (command icon) equals: self banana
```

**Pull request merged**
