### PR TITLE
748-Use-correct-Spec2-prefix-also-for-traits

### LINKED ISSUE #748: Use correct Spec2 prefix also for traits
Spec2 should be prefixed with "Sp" - this should be true also for the traits. 
The order is first the prefix "Sp" and then the "T" like Traits as the prefix acts like a namespace.

So the following traits need to be renamed
```
TSpDynamicPresenter -> SpTDynamicPresenter
TSpHaveWrappingScrollBars -> SpTHaveWrappingScrollBars
TSpObservable -> SpTObservable
TSpMorphicTableDataSourceCommons -> SpTMorphicTableDataSourceCommons
```

### PR DESCRIPTION
**Pull request by jecisc**
Use SpT prefix instead of TSp for traits.

Fixes #748

### CODE REVIEW

**Comment by jecisc** [comment]
I don't know why but this does not work in Pharo 7... :(

**Comment by astares** [comment]
Why not?

**Comment by jecisc** [comment]
```
MessageNotUnderstood: receiver of "asTraitComposition" is nil

UndefinedObject(Object)>>doesNotUnderstand: #asTraitComposition

MCClassDefinition>>traitCompositionCompiled

[ :builder | 

builder

	superclass: superClass;

	name: name;

	layoutClass: (ObjectLayout layoutForType: type);

	slots: self instanceVariables;

	sharedVariables: self classVariables;

	sharedPools: self sharedPoolsString;

	classSlots: self classInstanceVariables;

	traitComposition: self traitCompositionCompiled;

	classTraitComposition: self classTraitCompositionCompiled;

	comment: comment stamp: commentStamp;
```

I don't know yet the origin of the problem.

**Comment by jecisc** [comment]
We plan to remove TSpObservableSlot from Spec to push it in Pharo directly. We'll rename it when doing that. I'll wait for this to be integrated into Pharo before updating this PR.

**Comment by estebanlm** [comment]
I think this has been fixed upstream

**Pull request closed without merging**
