### PR TITLE
Do not refresh UI too often when using progress presenter.

### PR DESCRIPTION
**Pull request by demarey**
Without this change performance of the work block will be very impacted!

### CODE REVIEW

**Comment by estebanlm** [comment]
I have mixed feelings with the idea of exposing an attribute to control the refresh rate. Why not to make it a minimum in the adapter?

**Comment by demarey** [comment]
> I have mixed feelings with the idea of exposing an attribute to control the refresh rate. Why not to make it a minimum in the adapter?

There is a default reasonable value (250 ms). As we cannot guess all use cases, it is better to let people choose according to their needs: refresh only each 5 seconds (really slow job), or refresh each 100 ms (fast job).
The refresh rate really depends on what you will do.

**Comment by estebanlm** [comment]
yeah, you are answer me with a tautology, precisely what I have mixed feelings is to let the users choose ;)
anyway, tests are failing.

**Comment by estebanlm** [comment]
by the way, the refresh rate has sense if this is a minimum, not a forced rate.

**Comment by demarey** [comment]
I'm looking at the failing test.
It is failing because tests are not ran in the UI thread when using headless mode (they are run in UI thread when in headfull mode)

**Pull request merged**
