### PR TITLE
914-ChangeSorter-newChangeset-raises-an-error

### PR DESCRIPTION
**Pull request by Ducasse**
Fixes: 914 now newSet is working

### CODE REVIEW

**Comment by Ducasse** [comment]
Closed because there is a lot more to do

**Comment by estebanlm** [comment]
btw, now that we are integrating new tools, we need to move this Spec-Tools to NewTools project.

**Comment by estebanlm** [comment]
do we close this PR ?

**Comment by Ducasse** [comment]
Done!

**Pull request closed without merging**
