### PR TITLE
add icetray like presenters

### PR DESCRIPTION
**Pull request by demarey**
add a text input with validation (required field).
add a presenter to present a list of options and a dedicated panel (mac style) with optional validation

### CODE REVIEW

**Review by estebanlm — CHANGES_REQUESTED** [review]
I really do not want any of this as part of a `Spec-Core` package. It is not core! :)

**Comment by Ducasse** [comment]
We should put it in Common-widgets

**Comment by demarey** [comment]
> I really do not want any of this as part of a `Spec-Core` package. It is not core! :)

Why wouldn't it be core? 
All other widgets are there. And these widgets are not really different from others. I would keep them in Core so that people can find them easily, aside other presenters

**Comment by estebanlm** [comment]
because this are not core widget but composed ones. 
no, is not core, please move them to a separated package :)
In fact... there is already a `Spec2-CommonWidgets` package which is seriously more appropriate.

**Comment by demarey** [comment]
> because this are not core widget but composed ones. no, is not core, please move them to a separated package :) In fact... there is already a `Spec2-CommonWidgets` package which is seriously more appropriate.

`Spec2-CommonWidgets` package  is also a good place. Let's do that

**Pull request merged**
